# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:
  en: Resume - Pauline Argenson
  fr: CV - Pauline Argenson
email: pauline.argenson@gmail.com
description:
  en: Digital Marketing Cordinator looking for new challenges abroad
  fr: Digital Marketing Cordinator actuellement à la recherche de nouveaux challenges à l'international
index:
  en:
  fr: accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: none
posts_enabled: true

twitter_username: paulineargenson
github_username:  paulineargenson
google_analytics: UA-60615317-1

# Maintenance mode
maintenance: true
maintenance_message:
  en: Site under maintenance, coming back soon !
  fr: Site en maintenance, de retour très vite !

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

#sass:
style: compressed
